# Generated by Django 5.1.7 on 2025-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='employee',
        ),
        migrations.AddField(
            model_name='grant',
            name='employee_category',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_clerk', 'HR Clerk'), ('admin', 'System Admin')], default='employee', help_text='Select the employee category to which this grant applies.', max_length=20),
        ),
        migrations.AlterField(
            model_name='grant',
            name='allocated_hours',
            field=models.IntegerField(),
        ),
    ]
