# Generated by Django 5.1.7 on 2025-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_userleavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='adjacentdayrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='adjacentdayrestriction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consecutivedayrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='consecutivedayrestriction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='coworkerrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coworkerrestriction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dateexclusionrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dateexclusionrestriction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dayofweekrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dayofweekrestriction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='periodlimitrestriction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='periodlimitrestriction',
            name='location',
        ),
        migrations.AddField(
            model_name='adjacentdayrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='adjacentdayrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
        migrations.AddField(
            model_name='consecutivedayrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='consecutivedayrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
        migrations.AddField(
            model_name='coworkerrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='coworkerrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
        migrations.AddField(
            model_name='dateexclusionrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='dateexclusionrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
        migrations.AddField(
            model_name='dayofweekrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='dayofweekrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
        migrations.AddField(
            model_name='periodlimitrestriction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.category'),
        ),
        migrations.AddField(
            model_name='periodlimitrestriction',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_restrictions', to='leave.location'),
        ),
    ]
