# Generated by Django 5.1.7 on 2025-04-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_userleavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='grant',
        ),
    ]
